kind: Secret
apiVersion: v1
metadata:
  name: recipes
type: Opaque
data:
  # echo -n 'secret-key' | sha256sum | awk '{ printf $1 }' | base64
  secret-key: NmY2ODRhMjAzNTQ4ODRlY2NjZjhhOGViMzVkY2I1NzllNzUxNmY3ZDhhNDk3ZWEzZjhiZGE2YzFiOTgwNGJmZA==
